server:
  port: 8083

spring:
  application:
    name: CONFIG-SERVICE

  cloud:
    config:
      server:
        git:
          uri: https://github.com/SravanKumarNC/ConfiService_forMicroServices
          clone-on-start: true